receivers:
  systemd:

exporters:
  prometheus:
    endpoint: "localhost:9091"
    resource_to_telemetry_conversion:
      enabled: true
      
service:
  pipelines:
    metrics:
      receivers: [ systemd ]
      exporters: [ prometheus ]
